version: '3'

services:

  mysql-development:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: britishredcross
    ports:
      - "3308:3306"
  admin:
    image: adminer
    ports:
      - "8080:8080"
